# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_news', models.CharField(max_length=200)),
                ('text_news', models.TextField()),
                ('img_news', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации новости')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
