# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название поста')),
                ('text_post', models.TextField(verbose_name='Текст поста')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикацит поста')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления поста')),
            ],
            options={
                'verbose_name_plural': 'Посты',
                'verbose_name': 'Пост',
            },
        ),
        migrations.CreateModel(
            name='Images_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_photo', models.CharField(max_length=20, verbose_name='Название картики')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='картинка')),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
            options={
                'verbose_name_plural': 'Картинки',
                'verbose_name': 'Картинка',
            },
        ),
    ]
